version: '3.1'

services:

  dominios-ricos-db:
    image: postgres
    container_name: dominios-ricos-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"