version: '3.1'

services:

  dominios-ricos-psql-db:
    image: postgres
    container_name: dominios-ricos-psql-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  dominios-ricos-mongo-db:
    image: mongo
    container_name: dominios-ricos-mongo-db
    ports:
      - "27017:27017"