name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: qVWuuuscgeqiwDV6znLYoP8jbVsCpkjA:61fd69aa4b0cb1cd46bea520
           
          # OPTIONAL CONFIG, use if necessary
          oas-file-path: './swagger.json'
          api-version: 'v1.0.0'